//Manejo de los estados por componente
export const OBTENER_VEHICULO = 'OBTENER_VEHICULO'
//State para el pedido
export const SELECCIONAR_VEHICULO = 'SELECCIONAR_VEHICULO';

//types para el pedido
export const CONFIRMAR_VEHICULO = 'CONFIRMAR_VEHICULO'
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'
export const ELIMINAR_VEHICULO = 'ELIMINAR_VEHICULO'
export const CARGAR_CATALOGO = 'CARGAR_CATALOGO'
export const FILTER_VEHICLE = 'FILTER_VEHICLE'
export const OBTENER_HISTORIAL_SERVICIOS = 'OBTENER_HISTORIAL_SERVICIOS'